### ISSUE TITLE
Bulk license updater not working

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1520]
>[MO] Question From flowntheloop@gmail.com
webmaster mushroomobserver.org <webmaster@mushroomobserver.org>	Thu, Jun 1, 2023 at 8:02 AM
To: flowntheloop@gmail.com
Flown:
Thanks for letting us know about the problem.
I will be out all day, so I don't know when I can get around to helping you.
Joe (member, MO volunteer admin team)
>> On Thu, Jun 1, 2023 at 5:40 AM <webmaster@mushroomobserver.org> wrote:
    I am trying to use your bulk license updater to change all of my photo attribution to Non-Commercial use. This is happening after National Audubon Society snagged my photos from here without my permission. I was unaware that I would have to go back to previous observations and change settings to NC use manually.  Unfortunately your bulk updater is not working for me. Any help would be much appreciated.
    Kind regards, Flown

== https://www.pivotaltracker.com/story/show/185313081

**Comment by nimmolo** [comment]
Thanks Joe. From your diagnosis, which i believe is correct, it seems the form basically sends a usable hash of info, it's just not nested and accessible under the attribute `updates` as the controller is expecting.  I can hopefully handle next week if it's not too urgent, but I'd be glad if you want to. There seem to be two possible fixes.1. Change the form builder to do a block like `fields_for(:updates) do bla end` in whatever part of the form's assembling the array of images. Even easier, you may be able to just declare `form_with(scope:updates, ...)` at the top of the form, if it doesnt have other params. (im not going to try to read the form template on my phone. )2. Change the images::licenses controller to parse the current hash thats being sent, ie the numbered params. Doesnt seem safe because the numbers are ambiguousOn Jun 1, 2023, at 4:53 PM, Joseph D. Cohen ***@***.***> wrote:﻿
It's a view issue:
NoMethodError in Images::LicensesController#update
undefined method `each_value' for nil:NilClass
Extracted source (around line #1068):
  def self.process_license_changes_for_user(user, updates)
    updates.each_value do |row|
      next unless row_changed?(row)

      images_to_update = Image.where(

...
Application Trace | Framework Trace | Full Trace
app/models/image.rb:1068:in `process_license_changes_for_user'
app/controllers/images/licenses_controller.rb:23:in `update'
app/controllers/application_controller.rb:241:in `catch_errors_and_log_request_stats'
It's expecting params that include: [updates: {1: ...}, {2: ... } ...], but the returned params omit the updates hash, returning just the numbered rows. Example:
{"utf8"=>"✓",
...
 "_method"=>"put",
 "1"=>{"new_holder"=>"Joseph D. Cohen", "old_holder"=>"Joseph D. Cohen", "new_id"=>"2", "old_id"=>"3"},
 "2"=>{"new_holder"=>"Oregon Mycological Society", "old_holder"=>"Oregon Mycological Society", "new_id"=>"3", "old_id"=>"3"},
 "3"=>{"new_holder"=>"Sava Krstic", "old_holder"=>"Sava Krstic", "new_id"=>"3", "old_id"=>"3"},
...
 "commit"=>"Update"}

**Comment by nimmolo** [comment]
Not as hard as i figured to read the form template on a phone. so - It already has `form_with scope: :updates do |f|` — the problem is that the loop with `fields_for("#{row})` flattens that nesting and declares another top-level param. To maintain nesting with `fields_for`, line 39 just needs to be `<%= f.fields_for("#{row}") do |f_r| %>`That's it. One-line change. On Jun 1, 2023, at 9:30 PM, nimmo ***@***.***> wrote:﻿Thanks Joe. From your diagnosis, which i believe is correct, it seems the form basically sends a usable hash of info, it's just not nested and accessible under the attribute `updates` as the controller is expecting.  I can hopefully handle next week if it's not too urgent, but I'd be glad if you want to. There seem to be two possible fixes.1. Change the form builder to do a block like `fields_for(:updates) do bla end` in whatever part of the form's assembling the array of images. Even easier, you may be able to just declare `form_with(scope:updates, ...)` at the top of the form, if it doesnt have other params. (im not going to try to read the form template on my phone. )2. Change the images::licenses controller to parse the current hash thats being sent, ie the numbered params. Doesnt seem safe because the numbers are ambiguousOn Jun 1, 2023, at 4:53 PM, Joseph D. Cohen ***@***.***> wrote:﻿
It's a view issue:
NoMethodError in Images::LicensesController#update
undefined method `each_value' for nil:NilClass
Extracted source (around line #1068):
  def self.process_license_changes_for_user(user, updates)
    updates.each_value do |row|
      next unless row_changed?(row)

      images_to_update = Image.where(

...
Application Trace | Framework Trace | Full Trace
app/models/image.rb:1068:in `process_license_changes_for_user'
app/controllers/images/licenses_controller.rb:23:in `update'
app/controllers/application_controller.rb:241:in `catch_errors_and_log_request_stats'
It's expecting params that include: [updates: {1: ...}, {2: ... } ...], but the returned params omit the updates hash, returning just the numbered rows. Example:
{"utf8"=>"✓",
...
 "_method"=>"put",
 "1"=>{"new_holder"=>"Joseph D. Cohen", "old_holder"=>"Joseph D. Cohen", "new_id"=>"2", "old_id"=>"3"},
 "2"=>{"new_holder"=>"Oregon Mycological Society", "old_holder"=>"Oregon Mycological Society", "new_id"=>"3", "old_id"=>"3"},
 "3"=>{"new_holder"=>"Sava Krstic", "old_holder"=>"Sava Krstic", "new_id"=>"3", "old_id"=>"3"},
...
 "commit"=>"Update"}

**Comment by pellaea** [comment]
I'm glad you understood all of that!  Thanks, Nimmo.

**Comment by JoeCohen** [comment]
@nimmolo: Thanks for the tips! 
I'll see if I can deal with it today. 
(It already has `form_with(scope:updates, ...)` at the top of the form.)

**Comment by JoeCohen** [comment]
@nimmolo: I just noticed your second message with the precise fix.  Thanks a million!
I'll fix it and deploy this morning.
