### ISSUE TITLE
Location formatting not cached separately

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1860]
I first noticed this on the observations for the North Falmouth Project: https://mushroomobserver.org/observations?project=334 where most of the observation locations had the "Scientific" layout (e.g., USA, Massachusetts, Falmouth, North Falmouth), but one identified as "Stereum" (https://mushroomobserver.org/533313) was using the "Postal" layout (North Falmouth, Falmouth, Massachusetts, USA).  Initially I thought it might be something distinctive about the observation, but I now think it has to do with some of the new caching.  I was able to reproduce the behavior by going to the observations of another project (https://mushroomobserver.org/observations?project=295) after flipping my own location formatting choice to "Postal".  The first page, is now using "Postal".  I then switched to "Scientific" and the project the first page is still in "Postal" layout, but if I go to the second page, it rendered in "Scientific".  I was not able to reproduce this behavior locally, but can easily reproduce it in production.

@nimmolo hopefully this is something that you can sort out since I have no idea what's been going on with respect to caching.

**Comment by JoeCohen** [comment]
@nimmolo 
@mo-nathan explored this during today's tech meeting. 
It appears that was seeing stuff that was cached by Nathan.
- I looked at the first page of a Project's Observations. All the Locations were shown in Postal format (my default).
- Nathan then looked at other pages. (Note that Nathan and I have a different number of Observations per page, so any given page number is different between us.) The Locations were shown in Scientific format (Nathan's default).
- I then looked at pages which Nathan had just looked at. The Locations that were included in a page which Nathan had viewed were now in Scientific format.
#### Question: Does this mean that the Location must be cached per user?

**Comment by nimmolo** [comment]
Good catch, I forgot about location format.

HTML "fragment" or partial caching is already making the site much quicker, so it's a good time to read up on it if you haven't. I think it's going to be important for awhile. 

The key outline:
- Each version of a fragment, when it is rendered the first time, gets a unique identifying "key".
- The fragment goes on the top of the queue of fragments as soon as it's used. 
- When a page is rendered, it checks for the existence of a valid fragment in the queue - "valid" in this case means the `updated_at` segment of the "key" must match. 
- If the template uses that fragment, it is again placed on the top of the queue. 
- Fragments that are not used again make their way to the bottom of the queue.
- When the cache runs out of memory, it deletes fragments from the bottom of the queue up. 

As you can tell, the number of permutations of any given fragment (e.g.`matrix_box`) decreases the likelihood the fragment will be used again before expiring. So with fragment caching, we have to economize on the number of formats, otherwise fragments will expire when they essentially have the same content and still might be useful for others. 

We need different versions of each cached partial, at this point. But each "parameter" multiplies the number of permutations of the fragment by the number of possibilities for that param. On matrix boxes, we now have 32 possible permutations for a cached matrix_box:
- logged-in/no_user (2 total permutations)
- locale (16 total permutations)

It's easy to imagine how adding per-user caches will multiply this number: instead of `16x2` we'll have `16x{number of recent users}`. That will quickly fill up the cache queue. 

There are two possible solutions here. We could cache per location format (x2), which will double (to 64) the number of possible permutations per matrix box. 

Or we could wrap locations in an identifiable `<span>`, and use JS to flip the word order in the client's browser. I think that's the way to go.

By the way, Jason proposed the same solution for translation strings, which would radically simplify the cache! There are JS client-side translation libraries out there, and I'd like to do this. But that's quite a project. Let's try this first.

**Comment by JoeCohen** [comment]
Thanks for looking into this. The <span> + js solution sounds good. 
Who does the word-order flipping? Is it internal to js, or is supplying some argument to Rails? or something else?

**Comment by nimmolo** [comment]
@JoeCohen - this kind of JS action is not too different from Ruby code, except it runs in the browser after the user loads the page. It would be done in a Stimulus controller that would watch the browser window for the appearance of a location string, which we would mark in our templates with a CSS class like `location-format` on a `span` element. This is where we need to be diligent in adding these to the templates via a helper, I'm sure we will miss some at first. Also, we'd mark the `body` element with a css class indicating the current user's preference: `location-format-scientific`. If the JS finds both, it engages the method to rearrange.

The rearrange method in JS would take the content of the span and perform the same type of string-rearrangement method we do on the Ruby side, to split the location on the commas, and rearrange them back to front.

**Comment by JoeCohen** [comment]
@nimmolo: Thanks for the clear, extended explanation.

**Comment by mo-nathan** [comment]
@nimmolo Do you know how much space the cache is actually taking and how quickly things are rolling off?  Personally I would lean towards 2x-ing the cache for Scientific/Postal over duplicating logic, adding extra mechanism, and potentially slowing down the rendering (all be it not by much).  It would also be helpful to know how many cases commonly happen.  I did a quick look at the db and we have around 120 users using the Scientific format and I would guess those are disproportionately active users.

**Comment by nimmolo** [comment]
I can't tell how much space it's taking up. The cache is currently using server RAM via `memcached`, but I'm planning to make it get a lot larger by caching the show obs partials. i don't know if flipping location strings is a good reason to double the cache... unless we change cache formats! (I don't even feel that the image vote UI is worth doubling the cache size, as it currently does.) Reversing location strings in JS, or hiding the image vote UI, is trivially fast and easy with Stimulus.

I brought this up last week on a MO Dev thread that didn't get any response: i believe there is a better solution that gives us a ton of cache space, where we can cache all we like: `solid_cache`, which uses its own cache db and allows for much _much_ longer cache expiration times. This gem setup will be the default cache in Rails 8. 

I think we'd want to set up a cache db on the production server, not the db server, because our db server is so damn slow, although I'm also working on that. But I'm a bit scared of running `rails db:create` on production, with the additional entry in `database.yml`. Should I be?

**Comment by pellaea** [comment]
I continue to be scared of running rails db:create on production, too.  Is
there any way to test it on dev first to see how the logistics of working
with two separate databases at the same time works in rails?  And, like,
what sanity checks / safeguards are in place to prevent one from
accidentally clobbering the live database?

**Comment by nimmolo** [comment]
There is definitely a way to test on dev first, recommended in the [gem setup](https://github.com/rails/solid_cache) readme. 

Creating secondary db's seems to be an increasingly common procedure in Rails, especially on larger sites. I think i just need to carefully read [the guide on `db:create` for multiple databases](https://guides.rubyonrails.org/active_record_multiple_databases.html) to feel more confident about it. 

But I figured Nathan may have been around for some secondary database creation at his work.

**Comment by pellaea** [comment]
Cool.  Yeah, I agree, I think it's just about seeing it work and then I'm
sure I'll be totally comfortale with it, too.

**Comment by mo-nathan** [comment]
Personally I've never used db:create to create multiple databases for the same project.  We have multiple databases at work, but only one Rails ORM database per project.  We do have read-only replicas, but I think that's different than what you are describing.  The other databases we use are for document search (Mongo or Solr).  As long as it gets tests, that's the important thing.

**Comment by mo-nathan** [comment]
Regarding the caching question, I think the important questions of maintainability and being DRY are the problem.  For MO these are particularly important since we are all volunteers and the folks who will be maintaining the system in future will not necessarily be familiar with all the tech we've chosen to use.  There is a reason that I didn't just go in a fix this bug when I saw it.  Specifically I don't know how this new caching mechanism gets managed.  While I appreciate the potential speed up, there is a cost to maintainability.  In my view we should be doing the simplest possible thing unless we have good evidence that the more complex solution is significantly better.  In my view calculating the location string in both Rails and JS is more complex than just adding to the cache.  If we don't know how big the cache is and how long the cache lasts, then we need to figure that out since that's the evidence we need to decide if it's worth it.  If the cache is never getting bigger than 10M and stuff doesn't roll out of it for a few days, then I don't care if we double it.  If the cache is taking 10G and stuff is rolling out of it in half an hour, then we shouldn't double it.  I'm sure it's somewhere in between those extremes, but we don't know where.

**Comment by nimmolo** [comment]
Thanks for the response, Nathan.

With the cache, DRY certainly goes both ways - there’s a case to be made that fewer variations makes for a DRYer cache. 

But I agree job 1 is finding out how big the cache currently is, please do let me know if you discover how to do that.

**Comment by mo-nathan** [comment]
There's an analogy between DRY code and avoiding duplicate cache items, but the point of DRY is all about developer maintainability not about storage vs performance.  Claiming that a smaller cache, more optimized cache is DRYer in some sense in my view misses the point of DRY as a software development concept.

**Comment by mo-nathan** [comment]
@nimmolo Looks like this is working again due to #1871.  Can this issue be closed?

**Comment by nimmolo** [comment]
Yes, thanks. Closing
