### ISSUE TITLE
Incorrect rss_log messages for Observation create and Name create

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#830]
1. When an Observation is created with an Image, the message is "Image added", but it should be "Observation Created".
2. When a species is created, the message is "Name updated" but it should be "Name Created".

**Comment by JoeCohen** [comment]
This is apparently related to the deletion of a clause in `app/presenters/matrix_box_presenter.rb` that checked to see if the object was just created (thanks @pellaea), and if so, it overrode the rss_log with the "object created" message, without creating something similar in `app/models/rss_log.rb`.

The deleted code `app/presenters/matrix_box_presenter.rb` lines 135-143 is:
```ruby
    elsif !time || time < target.created_at + 1.minute
      self.detail = :rss_created_at.t(type: target_type)
      unless [:observation, :species_list].include?(target_type)
        begin
          self.detail += " ".html_safe + :rss_by.t(user: target.user.legal_name)
        rescue StandardError
          nil
        end
      end
```
I think the equivalent in `app/models/rss_log.rb`, line-385-386 is:
```ruby
    elsif !time
      :rss_created_at.t(type: target_type)
```

**Comment by nimmolo** [comment]
That sounds correct @JoeCohen. So is it that too many messages are getting logged about a single observation with images being created, or is `detail` retrieving the wrong message? 

If it IS considered useful to have each added image logged to the associated obs, maybe the `detail` retrieval method could iterate back through the array of log messages, comparing timestamps with less than a >1minute difference and taking the first one.

I'm imagining for an observation created with images, the log messages would be like this:
image added 12:21:59
image added 12:21:21
image added 12:21:04
image added 12:20:40
observation created 12:20:25

**Comment by pellaea** [comment]
I think neither: I wouldn't say strictly speaking too many msgs are getting
logged.  And RssLog#detail is faithfully retrieving the latest.  I wouldn't
say either behavior is "wrong".  But we can definitely improve the behavior
for specific cases.

I love that you've simplified the code.  Now let's take a minute to
"re-fix" it correctly this time around.  I assume either Nathan or I wrote
the old code in the "whatever works" school of coding.  (Which admittedly
sounds much more like me than Nathan! :)

**Comment by pellaea** [comment]
Good point.  Excellent, in fact.  So why not change it on the other end?
That is, when RssLog actually logs the name, images, etc. after the
observation is created, have it check to see if the observation was just
created -- it definitely has access to that information! --  and silence
the superfluous log messages if so.  This happens only once: when the obs
is created.  Instead of many times (every time the obs log is shown).
Let's keep the display side clean and efficient.

**Comment by nimmolo** [comment]
Ok - so I followed the rabbit hole back from the method `RssLog.add_with_date` to `AbstractModel` methods `log`, `init_rss_log` and `log_create_image` - there's a lot to consider, but maybe the last of these seems to be the key point where you could test if the the created_at was recent. Will think about it more tomorrow!

**Comment by pellaea** [comment]
I think AbstractModel#log is the right place to do it if we are going to
fix it on that side.  Because there might be additional log messages at the
same time as the observation is created, not just the image creation.  (For
example, names, sequences, collection numbers, etc.)

You could just return (skip the log message) if the rss_log already exists
and created_at > 1.minute.ago.  (The first log message should be the
creation log, right?)

[No, I didn't try to look at this on github, just replied directly to the
github notification email.  Sorry.  I can see how that might result in
confusion if you edit the comment after the notification is sent.]

I am not wedded to any particular solution.  We're just exploring options.
If people feel like the log needs to be complete, then by all means tweak
the display end instead.  But don't tweak the parser.  Let's keep
RssLog#parse simple.  If we change RssLog#detail to handle this (the way we
did before this PR), then we might want to tweak the name of the method to
make it clear it's not just returning the latest log message anymore.
Maybe "latest_activity" instead?  Would that make it clearer that it's
being used by the Activity Log page?

Could rss_log.created_at be just as usable as rss_log.target.created_at?
That would solve the extra query problem.

**Comment by nimmolo** [comment]
> Could rss_log.created_at be just as usable as rss_log.target.created_at?
That would solve the extra query problem.

Whew. Doh! Yes I believe it would. I was halfway through writing a log message iterator method... 🤪
